### ISSUE TITLE
[JOSS Review] incorret command in tutorial

### ISSUE THREAD

**Issue by mjsull** [Bios4Biol/intronSeeker#9]
Hi, I think there is one minor error in the README

in the command "./intronSeeker findEvidence" some of the arguments use the files in the test dataset i.e. "data/Reduced_real_dataset" instead of the files created by the tutorial  i.e. "data/test_Reduced_real_dataset/"

Also the output writes to the Reduced_real_dataset instead of test_Reduced_real_dataset, not sure if this is intentional.

Best,

Mitch

**Comment by pbardou** [comment]
Hi Mitch,

You're right, it's a mistake. I've just corrected it in the README.
Thank you very much for your careful proofreading.

Best 

Philippe
